(in-package #:deflate-kit)

(deftype octets () '(simple-array (unsigned-byte 8) (*)))
(defun bytes (&rest xs) (make-array (length xs) :element-type '(unsigned-byte 8) :initial-contents xs))
(defun u16 (a i) (logior (aref a i) (ash (aref a (1+ i)) 8)))
(defun u32le (a i) (logior (aref a i) (ash (aref a (+ i 1)) 8)
                            (ash (aref a (+ i 2)) 16) (ash (aref a (+ i 3)) 24)))
(defun u32be (a i) (logior (ash (aref a i) 24) (ash (aref a (+ i 1)) 16)
                             (ash (aref a (+ i 2)) 8) (aref a (+ i 3))))
(defun append-byte (out b) (vector-push-extend (logand b 255) out))
(defun octet-vector () (make-array 128 :element-type '(unsigned-byte 8) :adjustable t :fill-pointer 0))
(defun ensure-limit (out limit)
  (when (and limit (> (length out) limit))
    (error 'deflate-output-limit :message "output limit" :limit limit)))

(defun crc32 (data &key (start 0) end)
  (let ((crc #xffffffff) (end (or end (length data))))
    (loop for i from start below end do
      (setf crc (logxor crc (aref data i)))
      (dotimes (j 8) (setf crc (if (logbitp 0 crc)
                                   (logxor (ash crc -1) #xedb88320)
                                   (ash crc -1)))))
    (logxor crc #xffffffff)))
(defun adler32 (data &key (start 0) end)
  (let ((a 1) (b 0) (end (or end (length data))))
    (loop for i from start below end do
      (setf a (mod (+ a (aref data i)) 65521)
            b (mod (+ b a) 65521)))
    (logior (ash b 16) a)))

(defstruct (bit-reader (:constructor make-br (data))) data (pos 0) (bits 0) (n 0))
(defun br-data (x) (bit-reader-data x))
(defun br-pos (x) (bit-reader-pos x))
(defun br-bits (x) (bit-reader-bits x))
(defun br-n (x) (bit-reader-n x))
(defun (setf br-pos) (v x) (setf (bit-reader-pos x) v))
(defun (setf br-bits) (v x) (setf (bit-reader-bits x) v))
(defun (setf br-n) (v x) (setf (bit-reader-n x) v))
(defun br-read (r n)
  (loop while (< (br-n r) n) do
    (when (>= (br-pos r) (length (br-data r))) (fail "truncated bit stream" (br-pos r)))
    (setf (br-bits r) (logior (br-bits r) (ash (aref (br-data r) (br-pos r)) (br-n r))))
    (incf (br-pos r)) (incf (br-n r) 8))
  (prog1 (logand (br-bits r) (1- (ash 1 n)))
    (setf (br-bits r) (ash (br-bits r) (- n)) (br-n r) (- (br-n r) n))))
(defun br-align (r) (let ((n (mod (br-n r) 8))) (when (plusp n) (br-read r n))))

(defstruct (bit-writer (:constructor make-bw (out))) out (bits 0) (n 0))
(defun bw-out (x) (bit-writer-out x))
(defun bw-bits (x) (bit-writer-bits x))
(defun bw-n (x) (bit-writer-n x))
(defun (setf bw-bits) (v x) (setf (bit-writer-bits x) v))
(defun (setf bw-n) (v x) (setf (bit-writer-n x) v))
(defun bw-write (w value n)
  (setf (bw-bits w) (logior (bw-bits w) (ash value (bw-n w)))) (incf (bw-n w) n)
  (loop while (>= (bw-n w) 8) do
    (append-byte (bw-out w) (logand (bw-bits w) 255))
    (setf (bw-bits w) (ash (bw-bits w) -8)) (decf (bw-n w) 8)))
(defun bw-finish (w)
  (when (plusp (bw-n w)) (append-byte (bw-out w) (logand (bw-bits w) 255))) (bw-out w))

(defun reverse-bits (x n) (let ((r 0)) (dotimes (i n r) (setf r (logior (ash r 1) (ldb (byte 1 i) x))))))
(defun huffman-table (lengths)
  (let* ((max (reduce #'max lengths)) (count (make-array (1+ max) :initial-element 0)) (next (make-array (1+ max) :initial-element 0)) (table (make-hash-table :test #'equal)))
    (loop for x across lengths when (plusp x) do (incf (aref count x)))
    (let ((code 0))
      (loop for bits from 1 to max do (setf code (ash (+ code (aref count (1- bits))) 1) (aref next bits) code)))
    (loop for sym from 0 below (length lengths) for len = (aref lengths sym) when (plusp len) do
      (setf (gethash (cons (reverse-bits (aref next len) len) len) table) sym) (incf (aref next len)))
    (values table max)))
(defun h-read (r table max)
  (let ((code 0))
    (loop for n from 1 to max do
      (setf code (logior code (ash (br-read r 1) (1- n))))
      (let ((x (gethash (cons code n) table))) (when x (return-from h-read x))))
    (fail "invalid Huffman code" (br-pos r))))
(defparameter *fixed-lit* nil)
(defparameter *fixed-dist* nil)
(defparameter *fixed-lm* nil)
(defparameter *fixed-dm* nil)
(defun fixed-tables ()
  (unless *fixed-lit*
    (multiple-value-setq (*fixed-lit* *fixed-lm*)
      (huffman-table (concatenate 'vector (loop repeat 144 collect 8) (loop repeat 112 collect 9) (loop repeat 24 collect 7) (loop repeat 8 collect 8))))
    (multiple-value-setq (*fixed-dist* *fixed-dm*)
      (huffman-table (make-array 32 :initial-element 5))))
  (values *fixed-lit* *fixed-lm* *fixed-dist* *fixed-dm*))
(defparameter *length-base* #(3 4 5 6 7 8 9 10 11 13 15 17 19 23 27 31 35 43 51 59 67 83 99 115 131 163 195 227 258))
(defparameter *length-extra* #(0 0 0 0 0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 0))
(defparameter *dist-base* #(1 2 3 4 5 7 9 13 17 25 33 49 65 97 129 193 257 385 513 769 1025 1537 2049 3073 4097 6145 8193 12289 16385 24577))
(defparameter *dist-extra* #(0 0 0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9 10 10 11 11 12 12 13 13))
(defun inflate-raw (data &key max-output)
  (let ((r (make-br data)) (out (octet-vector)) (last nil))
    (loop until last do
      (setf last (= 1 (br-read r 1)))
      (let ((type (br-read r 2)))
        (cond
          ((= type 0) (br-align r) (let ((n (br-read r 16)) (nn (br-read r 16)))
                                    (unless (= (logxor n #xffff) nn) (fail "stored block length mismatch"))
                                    (dotimes (i n) (append-byte out (br-read r 8)))))
          ((= type 1) (multiple-value-bind (lt lm dt dm) (fixed-tables) (inflate-codes r out lt lm dt dm max-output)))
          ((= type 2) (inflate-dynamic r out max-output))
          (t (fail "reserved DEFLATE block type")))))
    (ensure-limit out max-output) out))
(defun inflate-codes (r out lt lm dt dm max-output)
  (loop for sym = (h-read r lt lm) do
    (cond ((< sym 256) (append-byte out sym)) ((= sym 256) (return))
          ((> sym 285) (fail "invalid length symbol"))
          (t (let* ((ix (- sym 257)) (len (+ (aref *length-base* ix) (br-read r (aref *length-extra* ix))))
                     (ds (h-read r dt dm)) (dist (+ (aref *dist-base* ds) (br-read r (aref *dist-extra* ds)))))
               (when (> dist (length out)) (fail "distance exceeds output"))
               (dotimes (i len) (append-byte out (aref out (- (length out) dist)))))))
    (ensure-limit out max-output)))
(defun inflate-dynamic (r out max-output)
  (let* ((hlit (+ 257 (br-read r 5))) (hdist (+ 1 (br-read r 5))) (hclen (+ 4 (br-read r 4)))
         (order #(16 17 18 0 8 7 9 6 10 5 11 4 12 3 13 2 14 1 15)) (cl (make-array 19 :initial-element 0)))
    (dotimes (i hclen) (setf (aref cl (aref order i)) (br-read r 3)))
    (multiple-value-bind (ct cm) (huffman-table cl)
      (let ((all (make-array (+ hlit hdist))) (i 0) (prev 0))
        (loop while (< i (length all)) do
          (let ((s (h-read r ct cm)))
            (cond ((<= s 15) (setf (aref all i) s prev s) (incf i))
                  ((= s 16) (let ((n (+ 3 (br-read r 2)))) (when (or (zerop i) (> (+ i n) (length all))) (fail "bad repeat")) (dotimes (j n) (setf (aref all (+ i j)) prev)) (incf i n)))
                  ((= s 17) (let ((n (+ 3 (br-read r 3)))) (incf i n) (setf prev 0)))
                  ((= s 18) (let ((n (+ 11 (br-read r 7)))) (incf i n) (setf prev 0)))
                  (t (fail "invalid code-length symbol")))))
        (multiple-value-bind (lt lm) (huffman-table (subseq all 0 hlit))
          (multiple-value-bind (dt dm) (huffman-table (subseq all hlit)) (inflate-codes r out lt lm dt dm max-output)))))))

(defun inflate (data &key max-output (raw t))
  (declare (ignore raw)) (inflate-raw data :max-output max-output))

(defun fixed-code (symbol)
  (cond ((<= symbol 143) (values (+ #x30 symbol) 8)) ((<= symbol 255) (values (+ #x190 (- symbol 144)) 9))
        ((<= symbol 279) (values (- symbol 256) 7)) (t (values (+ #xc0 (- symbol 280)) 8))))
(defun deflate (data &key (level 6) (raw t) (sync-flush nil))
  (declare (ignore level raw sync-flush))
  (let ((out (octet-vector)) (w nil) (n (length data)) (i 0))
    (setf w (make-bw out)) (bw-write w 1 1) (bw-write w 1 2)
    (loop while (< i n) do
      (let ((best-len 0) (best-dist 0) (limit (min 258 (- n i))))
        (when (>= i 3)
          (loop for j from (max 0 (- i 32768)) below i do
            (when (and (= (aref data j) (aref data i)) (= (aref data (1+ j)) (aref data (1+ i)))
                       (= (aref data (+ j 2)) (aref data (+ i 2))))
              (let ((l 3)) (loop while (and (< l limit) (= (aref data (+ j (mod l (- i j)))) (aref data (+ i l)))) do (incf l))
                (when (> l best-len) (setf best-len l best-dist (- i j)))))))
        (if (>= best-len 3)
            (let ((li (position-if (lambda (x) (<= x best-len)) *length-base* :from-end t)) (dsi (position-if (lambda (x) (<= x best-dist)) *dist-base* :from-end t)))
              (multiple-value-bind (c bits) (fixed-code (+ 257 li)) (bw-write w (reverse-bits c bits) bits))
              (bw-write w (- best-len (aref *length-base* li)) (aref *length-extra* li))
              (bw-write w (reverse-bits dsi 5) 5)
              (bw-write w (- best-dist (aref *dist-base* dsi)) (aref *dist-extra* dsi)) (incf i best-len))
            (progn (multiple-value-bind (c bits) (fixed-code (aref data i)) (bw-write w (reverse-bits c bits) bits)) (incf i)))))
    (multiple-value-bind (c bits) (fixed-code 256) (bw-write w (reverse-bits c bits) bits)) (bw-finish w)))

(defun zlib-decompress (data &key max-output)
  (when (< (length data) 6) (fail "truncated zlib stream"))
  (let ((cmf (aref data 0)) (flg (aref data 1)))
    (unless (and (= (logand cmf #xf) 8) (zerop (mod (+ (ash cmf 8) flg) 31))) (fail "invalid zlib header"))
    (let* ((raw (subseq data 2 (- (length data) 4))) (out (inflate-raw raw :max-output max-output)) (want (u32be data (- (length data) 4))))
      (unless (= want (adler32 out)) (fail "zlib Adler-32 mismatch")) out)))
(defun zlib-compress (data &key (level 6))
  (let ((raw (deflate data :level level)) (out (octet-vector)))
    (append-byte out #x78) (append-byte out (if (<= level 1) #x01 (if (>= level 9) #xda #x9c)))
    (loop for b across raw do (append-byte out b)) (let ((x (adler32 data))) (dotimes (i 4) (append-byte out (ldb (byte 8 (* 8 (- 3 i))) x)))) out))
(defun gzip-decompress (data &key max-output)
  (let ((pos 0) (all (octet-vector)))
    (loop while (< pos (length data)) do
      (when (< (- (length data) pos) 18) (fail "truncated gzip member"))
      (unless (and (= (aref data pos) #x1f) (= (aref data (1+ pos)) #x8b) (= (aref data (+ pos 2)) 8)) (fail "invalid gzip header"))
      (let ((flg (aref data (+ pos 3))) (p (+ pos 10)))
        (when (logbitp 2 flg) (let ((n (u16 data p))) (incf p (+ 2 n))))
        (when (logbitp 3 flg) (loop while (not (zerop (aref data p))) do (incf p)) (incf p))
        (when (logbitp 4 flg) (loop while (not (zerop (aref data p))) do (incf p)) (incf p))
        (when (logbitp 1 flg) (incf p 2))
        (let* ((end (- (length data) 8)) (part (inflate-raw (subseq data p end) :max-output (and max-output (- max-output (length all))))))
          (unless (= (u32le data end) (crc32 part)) (fail "gzip CRC-32 mismatch"))
          (loop for b across part do (append-byte all b)) (setf pos (+ end 8)))) ) all))
(defun gzip-compress (data &key (level 6))
  (let ((raw (deflate data :level level)) (out (octet-vector)))
    (dolist (x '(#x1f #x8b 8 0 0 0 0 0 0 3)) (append-byte out x))
    (loop for b across raw do (append-byte out b))
    (let ((c (crc32 data)) (n (length data))) (dolist (x (list c (ash c -8) (ash c -16) (ash c -24) n (ash n -8) (ash n -16) (ash n -24))) (append-byte out x))) out))

(defstruct (inflate-stream (:constructor %make-inflate-stream)) chunks max-output)
(defun make-inflate-stream (&key max-output) (%make-inflate-stream :max-output max-output))
(defun inflate-stream-push (s data) (push data (inflate-stream-chunks s)) nil)
(defun inflate-stream-finish (s) (inflate (apply #'concatenate '(vector) (nreverse (inflate-stream-chunks s))) :max-output (inflate-stream-max-output s)))
(defstruct (deflate-stream (:constructor %make-deflate-stream)) chunks level)
(defun make-deflate-stream (&key (level 6)) (%make-deflate-stream :level level))
(defun deflate-stream-push (s data) (push data (deflate-stream-chunks s)) nil)
(defun deflate-stream-finish (s) (deflate (apply #'concatenate '(vector) (nreverse (deflate-stream-chunks s))) :level (deflate-stream-level s)))
