(in-package #:deflate-kit/test)

(defun %octets (string)
  (map '(vector (unsigned-byte 8)) #'char-code string))

(defun %assert-condition (type thunk)
  (handler-case
      (progn (funcall thunk) (error "Expected ~S" type))
    (condition (condition)
      (unless (typep condition type)
        (error "Expected ~S, got ~S" type (type-of condition))))))

(defun %write-octets (pathname octets)
  (with-open-file (stream pathname :direction :output :if-exists :supersede
                          :element-type '(unsigned-byte 8))
    (write-sequence octets stream)))

(defun %read-octets (pathname)
  (with-open-file (stream pathname :element-type '(unsigned-byte 8))
    (let ((output (make-array (file-length stream)
                              :element-type '(unsigned-byte 8))))
      (read-sequence output stream)
      output)))

(defun %pattern-octets (length)
  (let ((output (make-array length :element-type '(unsigned-byte 8))))
    (loop for i below length
          do (setf (aref output i) (char-code
                                    (char "the quick brown fox jumps over the lazy dog "
                                          (mod i 44)))))
    output))

(defun %random-octets (length)
  (let ((output (make-array length :element-type '(unsigned-byte 8)))
        (state 2463534242))
    (loop for i below length
          do (setf state (logand #xffffffff (+ (* state 1664525) 1013904223))
                   (aref output i) (ldb (byte 8 24) state)))
    output))

(defun %gzip-header-end (gzip)
  (let ((flags (aref gzip 3))
        (index 10))
    (when (logtest flags 4)
      (incf index (+ 2 (logior (aref gzip index)
                               (ash (aref gzip (1+ index)) 8)))))
    (dolist (flag '(8 16))
      (when (logtest flags flag)
        (loop until (zerop (aref gzip index))
              do (incf index))
        (incf index)))
    index))

(defun %gzip-with-extra (gzip)
  (let ((header (copy-seq (subseq gzip 0 10))))
    (setf (aref header 3) (logior (aref header 3) 4))
    (concatenate '(vector (unsigned-byte 8))
                 header #(3 0 1 2 3)
                 (subseq gzip 10))))

(defun %gzip-with-header-crc (gzip &key corrupt)
  (let* ((header-end (%gzip-header-end gzip))
         (header (copy-seq (subseq gzip 0 header-end)))
         (body (subseq gzip header-end))
         (header-crc nil))
    (setf (aref header 3) (logior (aref header 3) 2))
    (setf header-crc (logand (crc32 header) #xffff))
    (when corrupt (setf header-crc (logxor header-crc #xff)))
    (concatenate '(vector (unsigned-byte 8)) header
                 (vector (ldb (byte 8 0) header-crc)
                         (ldb (byte 8 8) header-crc))
                 body)))

(defun %gzip-executable ()
  "gzip")

(defun %external-gzip-round-trip (input &key (level 6) no-name)
  (let* ((directory (uiop:temporary-directory))
         (stem (format nil "cl-deflate-kit-~D" (get-internal-real-time)))
         (source (merge-pathnames (format nil "~A-input" stem) directory))
         (compressed (merge-pathnames (format nil "~A.gz" stem) directory))
         (decoded (merge-pathnames (format nil "~A-output" stem) directory))
         (gzip (%gzip-executable)))
    (unwind-protect
         (progn
           (%write-octets source input)
           (let ((ours (gzip-compress input :level level)))
             (%write-octets compressed ours)
             (uiop:run-program (list gzip "-dc" (namestring compressed))
                              :output decoded :error-output :string)
             (assert (equalp input (%read-octets decoded))))
           (uiop:run-program (append (list gzip)
                                     (if no-name '("-9" "-n") nil)
                                     (list "-c" (namestring source)))
                            :output compressed :error-output :string)
           (assert (equalp input (gzip-decompress (%read-octets compressed)))))
      (dolist (pathname (list source compressed decoded))
        (when (probe-file pathname) (delete-file pathname))))))

(defun %streaming-one-byte-round-trip (input)
  (let ((deflater (make-deflater :level 6)))
    (loop for octet across input
          do (deflater-write deflater
                             (make-array 1 :element-type '(unsigned-byte 8)
                                         :initial-contents (list octet)))
             (deflater-flush deflater))
    (deflater-finish deflater)
    (assert (equalp input (inflate (deflater-output deflater))))))

(defun %assert-output-limit (compressed)
  (let ((caught nil))
    (handler-case (inflate compressed :max-output-bytes 4)
      (inflate-size-limit-exceeded (condition)
        (setf caught condition)))
    (assert caught)
    (assert (= 4 (deflate-output-limit-limit caught)))
    (assert (= 5 (inflate-error-observed caught)))))

(defun run-tests ()
  (let* ((input (%octets "hello hello hello hello"))
         (second (%octets "second member"))
         (raw (deflate input))
         (gzip (gzip-compress input :filename "hello.txt" :comment "kit test"))
         (member-2 (gzip-compress second))
         (zlib (zlib-compress input)))
    (assert (equalp input (inflate raw)))
    (assert (= #xcbf43926 (crc32 (%octets "123456789"))))
    (assert (= #x11e60398 (adler32 (%octets "Wikipedia"))))
    (assert (equalp input (gzip-decompress gzip)))
    (let ((extra (gzip-decompress (%gzip-with-extra gzip))))
      (assert (equalp input extra)))
    (let ((bad-extra (copy-seq (%gzip-with-extra gzip))))
      (setf (aref bad-extra 10) #xff
            (aref bad-extra 11) #xff)
      (%assert-condition 'invalid-container-error
                         (lambda () (gzip-decompress bad-extra))))
    (assert (equalp input
                    (gzip-decompress (%gzip-with-header-crc gzip))))
    (%assert-condition 'checksum-error
                       (lambda ()
                         (gzip-decompress
                          (%gzip-with-header-crc gzip :corrupt t))))
    (assert (equalp (concatenate '(vector (unsigned-byte 8)) input second)
                    (gzip-decompress (concatenate '(vector (unsigned-byte 8))
                                                  gzip member-2))))
    (assert (equalp input (zlib-decompress zlib)))
    (let ((bad (copy-seq gzip)))
      (setf (aref bad (- (length bad) 8))
            (logxor (aref bad (- (length bad) 8)) #xff))
      (%assert-condition 'checksum-error (lambda () (gzip-decompress bad))))
    (let ((bad (copy-seq zlib)))
      (setf (aref bad (1- (length bad)))
            (logxor (aref bad (1- (length bad))) #xff))
      (%assert-condition 'checksum-error (lambda () (zlib-decompress bad))))
    (%assert-condition 'unsupported-container-error
                       (lambda ()
                         (let ((dictionary (copy-seq zlib)))
                           (let* ((cmf (aref dictionary 0))
                                  (flg (logior (logand (aref dictionary 1) #xe0)
                                               #x20))
                                  (fcheck (mod (- 31 (mod (+ (ash cmf 8) flg)
                                                           31))
                                                31)))
                             (setf (aref dictionary 1) (logior flg fcheck)))
                           (zlib-decompress dictionary))))
    (%assert-condition 'inflate-size-limit-exceeded
                       (lambda () (gzip-decompress gzip :max-output 4)))
    (%assert-condition 'inflate-size-limit-exceeded
                       (lambda () (zlib-decompress zlib :max-output 4)))
    (%assert-condition 'inflate-invalid-data
                       (lambda () (inflate (make-array 1 :element-type '(unsigned-byte 8)
                                                        :initial-contents '(7)))))
    (%assert-condition 'inflate-invalid-data
                       (lambda () (inflate (subseq raw 0 (1- (length raw))))))
    (dolist (level '(0 1 3 6 9))
      (%external-gzip-round-trip (%pattern-octets 4097) :level level))
    (%external-gzip-round-trip (%pattern-octets 4097) :level 9 :no-name t)
    (dolist (size '(0 1 65535 65536 65537 131071))
      (let ((data (if (zerop size) (make-array 0 :element-type '(unsigned-byte 8))
                      (%pattern-octets size))))
        (assert (equalp data (inflate (deflate data))))
        (assert (equalp data (gzip-decompress (gzip-compress data))))
        (assert (equalp data (zlib-decompress (zlib-compress data))))))
    (let ((repetitive (%pattern-octets 131072))
          (random (%random-octets 131072)))
      (assert (< (length (deflate repetitive :level 6)) (length repetitive)))
      (assert (equalp random (inflate (deflate random :level 6)))))
    (%streaming-one-byte-round-trip (%pattern-octets 257))
    (%assert-output-limit (deflate (%pattern-octets 1024)))
    (%assert-condition 'inflate-size-limit-exceeded
                       (lambda ()
                         (inflate (deflate (%pattern-octets 4))
                                  :max-output-bytes 0)))
    (%assert-condition 'inflate-invalid-data
                       (lambda ()
                         (inflate (concatenate '(vector (unsigned-byte 8))
                                               raw #(0)))))
    (format t "FR-002 focused tests passed~%")
    t))
