(in-package #:deflate-kit/test)

(defun %octets (string)
  (map '(vector (unsigned-byte 8)) #'char-code string))

(defun %assert-condition (type thunk)
  (handler-case
      (progn (funcall thunk) (error "Expected ~S" type))
    (condition (condition)
      (unless (typep condition type)
        (error "Expected ~S, got ~S" type (type-of condition))))))

(defun %raw-deflate (data &key level)
  (values (deflate data :level level) (length data)))

(defun %raw-inflate-prefix (data &key (start 0) end max-output-bytes)
  (inflate data :start start :end end :max-output-bytes max-output-bytes))

(defun %write-octets (pathname octets)
  (with-open-file (stream pathname :direction :output :if-exists :supersede
                          :element-type '(unsigned-byte 8))
    (write-sequence octets stream)))

(defun %read-octets (pathname)
  (with-open-file (stream pathname :element-type '(unsigned-byte 8))
    (let ((output (make-array (file-length stream)
                              :element-type '(unsigned-byte 8))))
      (read-sequence output stream)
      output)))

(defun %gzip-executable ()
  "gzip")

(defun %external-gzip-round-trip (input)
  (let* ((directory (uiop:temporary-directory))
         (stem (format nil "cl-deflate-kit-~D" (get-internal-real-time)))
         (source (merge-pathnames (format nil "~A-input" stem) directory))
         (compressed (merge-pathnames (format nil "~A.gz" stem) directory))
         (decoded (merge-pathnames (format nil "~A-output" stem) directory))
         (gzip (%gzip-executable)))
    (unwind-protect
         (progn
           (%write-octets source input)
           (uiop:run-program (list gzip "-c" (namestring source))
                            :output compressed :error-output :string)
           (let ((from-gzip (%read-octets compressed)))
             (assert (equalp input (gzip-decompress from-gzip)))
             (uiop:run-program (list gzip "-dc" (namestring compressed))
                              :output decoded :error-output :string)
             (assert (equalp input (%read-octets decoded))))))
      (dolist (pathname (list source compressed decoded))
        (when (probe-file pathname) (delete-file pathname)))))

(defun run-tests ()
  (let* ((input (%octets "hello hello hello hello"))
         (second (%octets "second member"))
         (raw (deflate input))
         (gzip (gzip-compress input :filename "hello.txt" :comment "kit test"))
         (member-2 (gzip-compress second))
         (zlib (zlib-compress input)))
    (assert (equalp input (inflate raw)))
    (assert (= #xcbf43926 (crc32 (%octets "123456789"))))
    (assert (= #x11e60398 (adler32 (%octets "Wikipedia"))))
    (assert (equalp input (gzip-decompress gzip)))
    (assert (equalp (concatenate '(vector (unsigned-byte 8)) input second)
                    (gzip-decompress (concatenate '(vector (unsigned-byte 8))
                                                  gzip member-2))))
    (assert (equalp input (zlib-decompress zlib)))
    (let ((bad (copy-seq gzip)))
      (setf (aref bad (- (length bad) 8))
            (logxor (aref bad (- (length bad) 8)) #xff))
      (%assert-condition 'checksum-error (lambda () (gzip-decompress bad))))
    (let ((bad (copy-seq zlib)))
      (setf (aref bad (1- (length bad)))
            (logxor (aref bad (1- (length bad))) #xff))
      (%assert-condition 'checksum-error (lambda () (zlib-decompress bad))))
    (%assert-condition 'unsupported-container-error
                       (lambda ()
                         (let ((dictionary (copy-seq zlib)))
                           (let* ((cmf (aref dictionary 0))
                                  (flg (logior (logand (aref dictionary 1) #xe0)
                                               #x20))
                                  (fcheck (mod (- 31 (mod (+ (ash cmf 8) flg)
                                                           31))
                                                31)))
                             (setf (aref dictionary 1) (logior flg fcheck)))
                           (zlib-decompress dictionary))))
    (%assert-condition 'inflate-size-limit-exceeded
                       (lambda () (gzip-decompress gzip :max-output 4)))
    (%assert-condition 'inflate-size-limit-exceeded
                       (lambda () (zlib-decompress zlib :max-output 4)))
    (%external-gzip-round-trip input)
    (format t "checksum/container interoperability tests passed~%")
    t))
